### ISSUE TITLE
bug: cells, entries and the source chain not getting displayed on holochain `0.3`

### ISSUE THREAD

**Issue by c12i** [darksoil-studio/holochain-playground#8]
@guillemcordoba I noticed that happs now scaffolded on `0.3` have the `holochain-playground` not displaying any cells, entries and the source chain like it would before.

This is the error logged in the dev tools console

```
77b620bf.js:6718 Uncaught (in promise) TypeError: t.filter is not a function
    at fhe (77b620bf.js:6718:615196)
    at The.<anonymous> (77b620bf.js:6718:623386)
    at Generator.next (<anonymous>)
    at a (77b620bf.js:6718:612255)
```

If you could point me to the direction where this issue is emerging, I could help fix it

**Comment by guillemcordoba** [comment]
This should be working in the latest release.
